#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Brand Compliance Report Generator

set -e

echo "========================================"
echo "Brand Compliance Report Generator Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# VERIFY PYTHON
# ============================================

echo "Checking Python version..."
PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2)
echo -e "${GREEN}Python $PYTHON_VERSION detected${NC}"

# ============================================
# VERIFY PROJECT STRUCTURE
# ============================================

echo ""
echo "Verifying project structure..."

if [ ! -f "scripts/brand-check.py" ]; then
    echo -e "${RED}ERROR: scripts/brand-check.py not found!${NC}"
    exit 1
fi
echo -e "${GREEN}✓ scripts/brand-check.py found${NC}"

if [ ! -f "references/colors.md" ]; then
    echo -e "${RED}ERROR: references/colors.md not found!${NC}"
    exit 1
fi
echo -e "${GREEN}✓ references/colors.md found${NC}"

if [ ! -f "index.html" ]; then
    echo -e "${RED}ERROR: index.html not found!${NC}"
    exit 1
fi
echo -e "${GREEN}✓ index.html found (for HTML template reference)${NC}"

# ============================================
# TEST EXISTING FUNCTIONALITY
# ============================================

echo ""
echo "Testing existing brand-check.py..."

# Test that the script runs (it will exit 0 or 1, both are OK)
if python3 scripts/brand-check.py index.html --quiet >/dev/null 2>&1 || [ $? -eq 1 ]; then
    echo -e "${GREEN}✓ brand-check.py is executable${NC}"
else
    echo -e "${RED}ERROR: brand-check.py failed to run${NC}"
    exit 1
fi

# Run a quick test scan
echo "Running test scan on index.html..."
if python3 scripts/brand-check.py index.html --quiet; then
    echo -e "${GREEN}✓ Test scan completed successfully${NC}"
else
    echo -e "${YELLOW}⚠ Test scan found violations (this is normal)${NC}"
fi

# ============================================
# CREATE REPORTS DIRECTORY
# ============================================

echo ""
echo "Creating reports directory for historical tracking..."

if [ ! -d "reports" ]; then
    mkdir -p reports
    echo -e "${GREEN}✓ reports/ directory created${NC}"
else
    echo -e "${YELLOW}✓ reports/ directory already exists${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: AZMX Brand Skills"
echo "Script: scripts/brand-check.py"
echo "Python: $PYTHON_VERSION"
echo ""
echo "Next Steps:"
echo "  1. Implementation will extend brand-check.py"
echo "  2. New flags: --report, --format, --output, --with-trends"
echo "  3. Output formats: JSON, HTML, Markdown"
echo "  4. Historical reports stored in reports/"
echo ""
echo "Test current functionality:"
echo "  python3 scripts/brand-check.py index.html"
echo ""
echo "View help:"
echo "  python3 scripts/brand-check.py --help"
echo ""
