#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "AZMX Brand - Gallery Generator Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check Python3
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: python3 is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python3 found:${NC} $(python3 --version)"

# Check Pillow
if ! python3 -c "import PIL" 2>/dev/null; then
    echo -e "${YELLOW}Warning: Pillow (PIL) not installed${NC}"
    echo "Installing Pillow..."
    pip3 install Pillow
fi
echo -e "${GREEN}✓ Pillow installed${NC}"

# ============================================
# ENVIRONMENT READY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To regenerate the gallery with security meta tags:"
echo "  python3 scripts/rebuild-index.py"
echo ""
echo "To view the gallery:"
echo "  open index.html"
echo ""
echo "Generated HTML will include:"
echo "  - Content-Security-Policy (CSP) meta tags"
echo "  - SHA-256 hashes for inline scripts and styles"
echo "  - Referrer-Policy, X-Frame-Options, X-Content-Type-Options"
echo ""
